apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app.kubernetes.io/name: MyApp
    app: mmseqs2-db
spec:
  selector:
    app: mmseqs2-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
