apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}

