# pip-audit: checks Python deps against the Python advisory DB (OSV), complements Dependabot PRs.
name: pip-audit

on:
  pull_request:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "15 3 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit (SARIF)
        run: pip-audit -r requirements.txt --format sarif --output pip-audit.sarif || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif
